[workspace]
resolver = "2"
members = ["docker", "dotnet", "git", "github", "gitlab", "moonlit", "nodejs", "semantic-release", "slack", "test-support"]

[workspace.package]
version = "0.1.0"
edition = "2021"
rust-version = "1.97"
license = "MIT OR Apache-2.0"
authors = ["Wolfware LLC"]
repository = "https://github.com/wolfware-labs/moonlit-plugins"

[profile.release]
opt-level = "s"
