[package]
name = "moonlit-plugin-docker"
version = "0.1.0"
edition = "2021"
rust-version = "1.97"
license = "MIT OR Apache-2.0"
publish = false
description = "Moonlit first-party docker plugin."

[lib]
name = "docker"
crate-type = ["cdylib"]

[dependencies]
moonlit-sdk = "0.3"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
schemars = "1"

[dev-dependencies]
tempfile = "3"
moonlit-engine = { git = "https://github.com/wolfware-labs/moonlit", rev = "4262dfce5148676f8bc12ff7c0e282ae9ce1d4cd" }
tokio = { version = "1", features = ["macros", "rt-multi-thread"] }
assert_cmd = "2"
predicates = "3"

[features]
cli-e2e = []
